name: super-linter
on: 
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  linter:
    runs-on: self-hosted
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master # １
        with: # ２ アクションの入力パラメータを指定
          host: ${{ secrets.SSH_HOST }} # ホスト名
          username: ${{ secrets.SSH_USERNAME }} # SSH ユーザ名
          key: ${{ secrets.SSH_PRIVATE_KEY }} # 秘密鍵の内容
          port: ${{ secrets.SSH_PORT }} # ポート番号
          script: |
            ssh jphacks
            cd /home/jphacks/KB_2312
            git switch main
            git pull origin main
            cd /home/jphacks/KB_2312/server
            screen -S deployment -X stuff '^C'
            screen -UAmdS deployment cargo run
            
