name: super-linter
on: 
  push:
    branches-ignore: [main, develop]
  workflow_dispatch:

jobs:
  linter:
    runs-on: self-hosted
    steps:
    ## exmpansion
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint code
      ## linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # ACTIONS_RUNNER_DEBUG: true
          DEFAULT_BRANCH: main
          OUTPUT_FORMAT: tap
          OUTPUT_DETAILS: detailed
          DISABLE_ERRORS: true
          VALIDATE_ALL_CODEBASE: true
          
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          # VALIDATE_RUST_2015: true
          # VALIDATE_RUST_2018: true
          VALIDATE_RUST_2021: true
          # VALIDATE_RUST_CLIPPY: true
      ## make docs
      - name: upload reports  
        uses: actions/upload-artifact@v2
        with:
          name: linter
          path: linter.report/
